"""add customer fields

Revision ID: 2134f0ed62e5
Revises: 1a8c3af3a446
Create Date: 2026-07-18 14:35:20.478497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2134f0ed62e5'
down_revision: Union[str, Sequence[str], None] = '1a8c3af3a446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('customers', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'address')
    op.drop_column('customers', 'phone')
    op.drop_column('customers', 'name')
    # ### end Alembic commands ###
