"""add reference_number to payments

Revision ID: d422c29155d6
Revises: 2134f0ed62e5
Create Date: 2026-07-18 16:07:01.754001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd422c29155d6'
down_revision: Union[str, Sequence[str], None] = '2134f0ed62e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('reference_number', sa.String(length=100), nullable=True))
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('payments', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('payments', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('payments', 'reference_number')
    # ### end Alembic commands ###
